### PR TITLE
Update to Storybook 8

### LINKED ISSUE #105: Storybook 8 compatibility
Hey @lifeiscontent! I’m reaching out from the SB core team :)

Storybook 8 (our next major release) is coming soon, and it introduces some breaking changes that your addon might need to account for.

We’ve listed all the key changes in [a new Storybook 8 migration guide](https://storybook.js.org/docs/8.0/addons/addon-migration-guide#key-changes-for-addons), and we’d encourage you to check it out and see if your addon is impacted.

We also have an addons channel in our Discord community, which we’d like to use to better communicate with addon authors in the future. If you’re not part of the server, consider joining [here](https://discord.gg/wMff8FkF) and message me (@joevaugh4n) so that I can give you the addon creator role! If you’re already in the server, please just ping me and I’ll respond to you there.

Thanks for being a part of our addon community!

Joe

### PR DESCRIPTION
**Pull request by skos-ninja**
Fixes #105.

Tested locally to be working within our internal project.
I've bumped to `6.0` to match the same versioning used previously

### CODE REVIEW

**Comment by shamoons** [comment]
Looking forward to this getting merged in

**Comment by shamoons** [comment]
Wondering if we can get this merged in @lifeiscontent ?

**Review by lifeiscontent — APPROVED** [review]

**Comment by lifeiscontent** [comment]
@shamoons @skos-ninja released! Let me know if you run into any issues.

Thanks for the help @skos-ninja 🎉

**Comment by skos-ninja** [comment]
Cheers @lifeiscontent. Looks like the publish action failed sadly: https://github.com/lifeiscontent/storybook-addon-apollo-client/actions/runs/8494164493/job/23268972357

**Comment by lifeiscontent** [comment]
ah, let me pull it down and manually publish. looks like I'll need to update the CI scripts

**Comment by lifeiscontent** [comment]
@skos-ninja ah, it was because you'd manually changed the version, the CI action does that for us 😅

**Comment by lifeiscontent** [comment]
should be fixed now!

**Pull request merged**
