### PR TITLE
Upgrade React version dependency

### PR DESCRIPTION
**Pull request by carlosbaraza**

### CODE REVIEW

**Comment by carlosbaraza** [comment]
#73

**Comment by lpgera** [comment]
Hey @lifeiscontent!
Could you please look at this PR and consider merging and then publishing a new version? This is the only thing blocking me from updating my projects to React version 18.

**Comment by lifeiscontent** [comment]
@lpgera still waiting on storybook to make upgrades, but I created a PR to get the ball rolling: https://github.com/storybookjs/storybook/pull/18478

**Comment by lifeiscontent** [comment]
@carlosbaraza @lpgera please take a look at the latest release and let me know if it works for you.

**Comment by lpgera** [comment]
Thank you, version 4.0.12 works fine! 🎉

**Pull request merged**
