### PR TITLE
chore: allow compatible versions for @apollo/client and @storybook/*

### PR DESCRIPTION
**Pull request by boredland**
closes https://github.com/lifeiscontent/storybook-addon-apollo-client/issues/20

### CODE REVIEW

**Review by SabineMueller910 — APPROVED** [review]

**Comment by lifeiscontent** [comment]
@boredland why does devDependencies have an impact on user land? how would you solve this issue if someone used Apollo 2.x?

**Comment by boredland** [comment]
> but one thing I'd like to understand is why does devDependencies have an impact on userland? 

the impact for us is/was only really there for your dependency to `@apollo/client@3.3.5` - our yarn lock then had to contain both versions. the newer one we were using and the older one this addon defines. 

> how would you solve this issue if someone used Apollo 2.x (which this package should also support)

then it probably shouldn't be a version. I think in similar cases I saw "*" as a peerDependency version.
 
> the only reason `@apollo/client` it's a dependency in the first place is that I wanted some kind of guarantees of the types that come from apollo, but at this point it might make sense to make my own type and remove it as a dependency since there are different types that come from apollo depending on if you use v2 or v3
> 
> what do you think?

I mean.. there is multiple solutions for that. Either people themselves declare a "resolutions" object in their package.json and hard-lock apollo-client to v2. Or you make it just a (peer)Dependency with an even wider version range (sth along the lines of ">=2.0.0 <4") or, yes, get rid of the versions alltogether. I think I'd give the very wide version a try because I imagine the DX could be slightly better when you have the types installed.

**Comment by lifeiscontent** [comment]
@boredland thanks for the feedback. I'll go ahead and cut a release to this hopefully later tonight.

**Comment by lifeiscontent** [comment]
@boredland can you test out the latest version of storybook-addon-apollo-client and see if that fixes your issues? Thanks!

**Pull request merged**
